# Generated by Django 6.0 on 2025-12-18 20:59

import django.db.models.deletion
import terminusgps_payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, max_length=1024, verbose_name='description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('payment', terminusgps_payments.models.AuthorizenetPaymentField()),
                ('address', terminusgps_payments.models.AuthorizenetAddressField()),
                ('cprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to='terminusgps_payments.customerprofile', verbose_name='customer profile')),
            ],
            options={
                'verbose_name': 'payment profile',
                'verbose_name_plural': 'payment profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddressProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('address', terminusgps_payments.models.AuthorizenetAddressField()),
                ('cprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_profiles', to='terminusgps_payments.customerprofile', verbose_name='customer profile')),
            ],
            options={
                'verbose_name': 'address profile',
                'verbose_name_plural': 'address profiles',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('schedule', terminusgps_payments.models.AuthorizenetPaymentScheduleField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('aprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='terminusgps_payments.customeraddressprofile')),
                ('cprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='terminusgps_payments.customerprofile')),
                ('pprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='terminusgps_payments.customerpaymentprofile')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
