# Generated by Django 6.0 on 2026-01-07 19:24

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, max_length=1024, verbose_name='description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('expiry_date', models.DateField(blank=True)),
                ('card_code', models.CharField(blank=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=9)),
                ('routing_number', models.CharField(blank=True, max_length=17)),
                ('account_name', models.CharField(blank=True, max_length=22)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(blank=True, choices=[('checking', 'Checking account'), ('savings', 'Savings account'), ('businessChecking', 'Business checking account')])),
                ('cprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to='terminusgps_payments.customerprofile', verbose_name='customer profile')),
            ],
            options={
                'verbose_name': 'payment profile',
                'verbose_name_plural': 'payment profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddressProfile',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('cprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_profiles', to='terminusgps_payments.customerprofile', verbose_name='customer profile')),
            ],
            options={
                'verbose_name': 'address profile',
                'verbose_name_plural': 'address profiles',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('terminated', 'Terminated'), ('unknown', 'Unknown')], default='unknown')),
                ('trial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('total_occurrences', models.PositiveIntegerField(default=9999)),
                ('trial_occurrences', models.PositiveIntegerField(default=0)),
                ('interval_length', models.IntegerField(default=1, editable=False)),
                ('interval_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='months', editable=False)),
                ('aprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='terminusgps_payments.customeraddressprofile', verbose_name='address profile')),
                ('cprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='terminusgps_payments.customerprofile', verbose_name='customer profile')),
                ('pprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='terminusgps_payments.customerpaymentprofile', verbose_name='payment profile')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
