# Generated by Django 5.2.6 on 2025-09-03 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_occurrences', models.IntegerField(default=9999)),
                ('trial_occurrences', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionScheduleInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='months', max_length=6)),
                ('length', models.IntegerField(default=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=31, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=12)),
                ('address_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='terminusgps_payments.addressprofile')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='terminusgps_payments.customerprofile')),
                ('payment_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='terminusgps_payments.paymentprofile')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='subscription', to='terminusgps_payments.subscriptionschedule')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionschedule',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='terminusgps_payments.subscriptionscheduleinterval'),
        ),
    ]
