# Generated by Django 6.0.4 on 2026-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expires_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
