# Generated by Django 6.0 on 2025-12-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddressprofile',
            name='id',
            field=models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerpaymentprofile',
            name='id',
            field=models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
