# Generated by Django 5.2.6 on 2025-09-19 18:59

import terminusgps_payments.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressprofile',
            name='address',
            field=terminusgps_payments.models.fields.AuthorizenetAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paymentprofile',
            name='address',
            field=terminusgps_payments.models.fields.AuthorizenetAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paymentprofile',
            name='credit_card',
            field=terminusgps_payments.models.fields.AuthorizenetCreditCardField(blank=True, default=None, null=True),
        ),
    ]
