# Generated by Django 5.2.6 on 2025-09-03 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0002_subscriptionschedule_subscriptionscheduleinterval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentprofile',
            options={'verbose_name': 'payment profile', 'verbose_name_plural': 'payment profiles'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=24.99, max_digits=9),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='addressprofile',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_profiles', to='terminusgps_payments.customerprofile'),
        ),
        migrations.AlterField(
            model_name='paymentprofile',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profiles', to='terminusgps_payments.customerprofile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(default="Blake's Subscription", max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionscheduleinterval',
            name='length',
            field=models.IntegerField(default=1),
        ),
    ]
