# Generated by Django 5.2.6 on 2025-09-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0003_alter_paymentprofile_options_subscription_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionschedule',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='addressprofile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='paymentprofile',
            name='cc_last_4',
        ),
        migrations.RemoveField(
            model_name='paymentprofile',
            name='cc_type',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionSchedule',
        ),
        migrations.DeleteModel(
            name='SubscriptionScheduleInterval',
        ),
    ]
