# Generated by Django 5.2.6 on 2025-09-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_payments', '0004_remove_subscriptionschedule_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('terminated', 'Terminated')], default='active', max_length=16)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('address_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='terminusgps_payments.addressprofile')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='terminusgps_payments.customerprofile')),
                ('payment_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='terminusgps_payments.paymentprofile')),
            ],
        ),
    ]
