from datetime import date
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.test import RequestFactory, TestCase
from terminusgps.authorizenet import api
from terminusgps.authorizenet.service import AuthorizenetService

from terminusgps_payments import views
from terminusgps_payments.forms import CustomerAddressProfileCreateForm
from terminusgps_payments.models import (
    CustomerAddressProfile,
    CustomerPaymentProfile,
    CustomerProfile,
)


class AuthorizenetCreateViewTestCase(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user_data = {
            "first_name": "Test",
            "last_name": "User",
            "username": "testuser",
            "password": "super_secure_password1!",
            "email": "testuser@domain.com",
        }
        cls.customer_profile_data = {
            "email": cls.user_data["email"],
            "merchant_id": cls.user_data["first_name"],
            "description": "",
        }

    def setUp(self):
        user_data = self.user_data.copy()
        self.test_user = get_user_model().objects.create_user(**user_data)
        customer_profile_data = self.customer_profile_data.copy()
        customer_profile_data["user"] = self.test_user
        self.customer_profile = CustomerProfile(**customer_profile_data)
        self.customer_profile.save()
        self.view_cls = views.AuthorizenetCreateView
        self.test_service = AuthorizenetService()

    def tearDown(self):
        self.test_service.execute(
            api.delete_customer_profile(
                customer_profile_id=self.customer_profile.pk
            )
        )

    def test_get_initial(self):
        """Fails if :py:meth:`get_initial` doesn't provide required members."""
        request = RequestFactory().get("/address-profiles/create/")
        request.user = self.test_user
        view = self.view_cls(
            model=CustomerAddressProfile,
            form_class=CustomerAddressProfileCreateForm,
            template_name="terminusgps_payments/customeraddressprofile_create.html",
        )
        view.setup(request)
        initial = view.get_initial()
        self.assertIn("customer_profile", initial)


class SubscriptionCreateViewTestCase(TestCase):
    def setUp(self):
        self.test_service = AuthorizenetService()
        self.test_id = str(uuid4())[:23]
        self.test_user_data = {
            "first_name": "Test",
            "last_name": "User",
            "username": f"testuser_{self.test_id}",
            "password": "super_secure_password1!",
            "email": f"testuser_{self.test_id}@domain.com",
        }
        self.test_user = get_user_model().objects.create_user(
            **self.test_user_data.copy()
        )
        self.test_customer_profile_data = {
            "user": self.test_user,
            "email": self.test_user.email,
            "merchant_id": self.test_user.first_name,
            "description": f"[{self.test_id}]: Automatically generated by the terminusgps_payments test suite.",
        }
        self.test_customer_profile = CustomerProfile(
            **self.test_customer_profile_data.copy()
        )
        self.test_customer_profile.save()
        self.test_address_profile_data = {
            "customer_profile": self.test_customer_profile,
            "first_name": self.test_user.first_name,
            "last_name": self.test_user.last_name,
            "company": "TestUserCompany",
            "address": "123 Main St",
            "city": "Houston",
            "state": "TX",
            "country": "USA",
            "zip": "77065",
            "phone_number": "17139045620",
        }
        self.test_payment_profile_data = {
            "customer_profile": self.test_customer_profile,
            "first_name": self.test_user.first_name,
            "last_name": self.test_user.last_name,
            "company": "TestUserCompany",
            "address": "123 Main St",
            "city": "Houston",
            "state": "TX",
            "country": "USA",
            "zip": "77065",
            "phone_number": "17139045620",
            "card_number": "4111111111111111",
            "card_expiry": date(year=2039, month=12, day=1),
            "card_code": "444",
        }
        self.test_address_profile = CustomerAddressProfile(
            **self.test_address_profile_data.copy()
        )
        self.test_address_profile.save()
        self.test_payment_profile = CustomerPaymentProfile(
            **self.test_payment_profile_data.copy()
        )
        self.test_payment_profile.save()
        self.view_cls = views.SubscriptionCreateView

    def tearDown(self):
        self.test_customer_profile.delete()
        self.test_user.delete()

    def test_get_initial(self):
        """Fails if :py:meth:`get_initial` doesn't provide required members."""
        request = RequestFactory().get("/subscriptions/create/")
        request.user = self.test_user
        view = self.view_cls(
            template_name="terminusgps_payments/subscriptions/create.html"
        )
        view.setup(request)
        initial = view.get_initial()
        self.assertIn("start_date", initial)

    def test_get_form(self):
        """Fails if :py:meth:`get_form` doesn't set required attributes before returning the form."""
        other_user = get_user_model().objects.create_user(
            first_name="Other",
            last_name="User",
            username="otheruser",
            email="otheruser@domain.com",
            password="super_secure_password1!",
        )
        other_customer_profile = CustomerProfile()
        other_customer_profile.user = other_user
        other_customer_profile.email = other_user.email
        other_customer_profile.merchant_id = other_user.first_name
        other_customer_profile.save()
        test_data = self.test_address_profile_data.copy()
        test_data["customer_profile"] = other_customer_profile
        other_address_profile = CustomerAddressProfile(**test_data)
        other_address_profile.save()
        test_data = self.test_payment_profile_data.copy()
        test_data["customer_profile"] = other_customer_profile
        other_payment_profile = CustomerPaymentProfile(**test_data)
        other_payment_profile.save()

        request = RequestFactory().get("/subscriptions/create/")
        request.user = self.test_user
        view = self.view_cls(
            template_name="terminusgps_payments/subscriptions/create.html"
        )
        view.setup(request)
        form = view.get_form()
        self.assertIsNone(form.fields["address_profile"].empty_label)
        self.assertIsNone(form.fields["payment_profile"].empty_label)

        other_address_profile.delete()
        other_payment_profile.delete()
        other_customer_profile.delete()
        other_user.delete()
